import Contact from './components/Contact'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter, Overpass } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const overpass = Overpass({ subsets: ['latin']})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${overpass.className}`} >
        <Navbar />
        {children}
        <Contact />
        </body>
    </html>
  )
}
